sp:
  user-service:
    users: "[{\"id\":7, \"username\":\"abc\",\"password\":\"123\"},{\"id\":88, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"ghi\",\"password\":\"789\"}]"


spring:
  application:
    name: user-service
  cloud:
    config:
      override-none: true 
    
server:
  port: 8101
  

management:
  endpoints:
    web:
      exposure:
        include: refresh
        
          
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka1:2002/eureka
      #或者      ：外地地址

